// lib/mock-data.ts
// Frontend phase e real API er jaygay mock data use korbo
// Backend wire-up korar somoy ekhane API call diye replace korte hobe

export const MOCK_COMPANIES = [
  {
    id: 1,
    companyName: "Brain Station 23",
    websiteDomain: "brainstation-23.com",
    location: "Mohakhali, Dhaka",
    city: "Dhaka",
    techStack: "React, Node.js, AI, ML",
    overallRating: 4.6,
    workLifeRating: 4.5,
    salaryRating: 4.4,
    managementRating: 4.8,
    reviewCount: 47,
    isVerified: true,
    isClaimed: true,
    employeeCount: "200+",
    trustBadge: "Top 10 Work-Life Balance",
    logoUrl: null,
  },
  {
    id: 2,
    companyName: "EchoLogyx Ltd",
    websiteDomain: "echologyx.com",
    location: "Muradpur, Chattogram",
    city: "Chattogram",
    techStack: "React, Node.js, Go",
    overallRating: 4.5,
    workLifeRating: 4.6,
    salaryRating: 4.3,
    managementRating: 4.5,
    reviewCount: 23,
    isVerified: true,
    isClaimed: true,
    employeeCount: "51-200",
    trustBadge: "Remote-First Policy",
    logoUrl: null,
  },
  {
    id: 3,
    companyName: "Authentic Four Technology",
    websiteDomain: "authenticfour.com",
    location: "Agrabad, Chattogram",
    city: "Chattogram",
    techStack: "Python, Django, PyTorch",
    overallRating: 4.3,
    workLifeRating: 4.2,
    salaryRating: 4.1,
    managementRating: 4.7,
    reviewCount: 18,
    isVerified: true,
    isClaimed: false,
    employeeCount: "11-50",
    trustBadge: "Flexible Hours",
    logoUrl: null,
  },
  {
    id: 4,
    companyName: "W3 Eden",
    websiteDomain: "w3eden.com",
    location: "Kalpolok, Chittagong",
    city: "Chattogram",
    techStack: "WordPress, PHP, React",
    overallRating: 4.2,
    workLifeRating: 4.1,
    salaryRating: 4.0,
    managementRating: 4.4,
    reviewCount: 31,
    isVerified: true,
    isClaimed: true,
    employeeCount: "11-50",
    trustBadge: "Top 1% Leadership",
    logoUrl: null,
  },
  {
    id: 5,
    companyName: "Webermelon",
    websiteDomain: "webermelon.com",
    location: "Khulshi, Chattogram",
    city: "Chattogram",
    techStack: "React, Next.js, Tailwind",
    overallRating: 4.0,
    workLifeRating: 3.9,
    salaryRating: 3.8,
    managementRating: 4.3,
    reviewCount: 12,
    isVerified: false,
    isClaimed: false,
    employeeCount: "11-50",
    trustBadge: "Mentor Focus",
    logoUrl: null,
  },
  {
    id: 6,
    companyName: "Technext Limited",
    websiteDomain: "technext.it",
    location: "Shyamoli, Dhaka",
    city: "Dhaka",
    techStack: "React Native, AWS, Node.js",
    overallRating: 4.1,
    workLifeRating: 4.0,
    salaryRating: 4.2,
    managementRating: 4.0,
    reviewCount: 29,
    isVerified: true,
    isClaimed: true,
    employeeCount: "51-200",
    trustBadge: "Culture Winner",
    logoUrl: null,
  },
  {
    id: 7,
    companyName: "AuthLab",
    websiteDomain: "authlab.io",
    location: "Jalalabad R/A, Sylhet",
    city: "Sylhet",
    techStack: "Next.js, Tailwind, Go",
    overallRating: 4.4,
    workLifeRating: 4.5,
    salaryRating: 4.2,
    managementRating: 4.5,
    reviewCount: 15,
    isVerified: true,
    isClaimed: true,
    employeeCount: "11-50",
    trustBadge: "Transparent Ops",
    logoUrl: null,
  },
  {
    id: 8,
    companyName: "LabFry Technologies",
    websiteDomain: "labfry.com",
    location: "Moulovi Pukur Par, Chittagong",
    city: "Chattogram",
    techStack: "Flutter, Firebase, Node.js",
    overallRating: 3.8,
    workLifeRating: 3.7,
    salaryRating: 3.6,
    managementRating: 4.0,
    reviewCount: 9,
    isVerified: false,
    isClaimed: false,
    employeeCount: "11-50",
    logoUrl: null,
  },
  {
    id: 9,
    companyName: "InnoTech Solutions",
    websiteDomain: "innotech.com.bd",
    location: "Agrabad, Chattogram",
    city: "Chattogram",
    techStack: "Cloud Infra, Fintech",
    overallRating: undefined,
    workLifeRating: 0,
    salaryRating: 0,
    managementRating: 0,
    reviewCount: 2, // Privacy shield test — 3 er niche
    isVerified: false,
    isClaimed: false,
    employeeCount: "1-10",
    logoUrl: null,
  },
  {
    id: 10,
    companyName: "Kaz Software Bangladesh",
    websiteDomain: "kaz.com.bd",
    location: "Shantinagar, Dhaka",
    city: "Dhaka",
    techStack: "Java, Spring Boot, React",
    overallRating: 4.3,
    workLifeRating: 4.2,
    salaryRating: 4.5,
    managementRating: 4.1,
    reviewCount: 38,
    isVerified: true,
    isClaimed: true,
    employeeCount: "51-200",
    trustBadge: "Competitive Salary",
    logoUrl: null,
  },
  {
    id: 11,
    companyName: "Vivasoft Limited",
    websiteDomain: "vivasoftltd.com",
    location: "Kemal Ataturk Ave, Dhaka",
    city: "Dhaka",
    techStack: "React, Vue, Node.js, AWS",
    overallRating: 4.0,
    workLifeRating: 3.9,
    salaryRating: 4.1,
    managementRating: 4.0,
    reviewCount: 22,
    isVerified: true,
    isClaimed: true,
    employeeCount: "51-200",
    logoUrl: null,
  },
  {
    id: 12,
    companyName: "Robotry Bangladesh",
    websiteDomain: "robotrybd.com",
    location: "Agrabad, Chittagong",
    city: "Chattogram",
    techStack: "Python, ROS, IoT",
    overallRating: 3.9,
    workLifeRating: 3.8,
    salaryRating: 3.7,
    managementRating: 4.1,
    reviewCount: 7,
    isVerified: false,
    isClaimed: false,
    employeeCount: "11-50",
    logoUrl: null,
  },
];

export const MOCK_JOBS = [
  {
    id: 1,
    companyId: 1,
    companyName: "Brain Station 23",
    jobTitle: "Senior Full-Stack Engineer",
    jobDescription: "We are looking for an experienced Full-Stack Engineer to join our growing team...",
    salaryRangeMin: 80000,
    salaryRangeMax: 150000,
    techStack: "React, Node.js, PostgreSQL",
    status: "PUBLISHED",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
  },
  {
    id: 2,
    companyId: 2,
    companyName: "EchoLogyx Ltd",
    jobTitle: "Junior React Developer",
    jobDescription: "Join our remote-first team as a Junior React Developer...",
    salaryRangeMin: 30000,
    salaryRangeMax: 55000,
    techStack: "React, TypeScript, Tailwind",
    status: "PUBLISHED",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    companyId: 4,
    companyName: "W3 Eden",
    jobTitle: "WordPress Developer",
    jobDescription: "Looking for an experienced WordPress developer to build premium plugins...",
    salaryRangeMin: 40000,
    salaryRangeMax: 70000,
    techStack: "WordPress, PHP, WooCommerce",
    status: "PUBLISHED",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    companyId: 7,
    companyName: "AuthLab",
    jobTitle: "DevOps Engineer",
    jobDescription: "We need a skilled DevOps engineer to manage our cloud infrastructure...",
    salaryRangeMin: 70000,
    salaryRangeMax: 120000,
    techStack: "AWS, Docker, Kubernetes, Terraform",
    status: "PUBLISHED",
    createdAt: new Date(Date.now() - 0).toISOString(), // Today
  },
  {
    id: 5,
    companyId: 6,
    companyName: "Technext Limited",
    jobTitle: "Mobile App Developer (React Native)",
    jobDescription: "Join our team to build cross-platform mobile applications...",
    salaryRangeMin: 50000,
    salaryRangeMax: 90000,
    techStack: "React Native, Redux, Firebase",
    status: "PUBLISHED",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    companyId: 10,
    companyName: "Kaz Software Bangladesh",
    jobTitle: "Backend Engineer (Java)",
    jobDescription: "We are looking for a Java backend engineer to work on our enterprise software...",
    salaryRangeMin: 60000,
    salaryRangeMax: 100000,
    techStack: "Java, Spring Boot, MySQL",
    status: "PUBLISHED",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_REVIEWS = [
  {
    id: 1,
    companyId: 1,
    isAnonymous: true,
    workLifeRating: 5,
    salaryRating: 4,
    managementRating: 5,
    reviewText:
      "Brain Station 23 is genuinely one of the best places to work in Bangladesh. Management is transparent, salaries are competitive for the market, and the work-life balance is real — not just on paper. They actually push you to leave on time.",
    voteScore: 24,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    companyId: 1,
    isAnonymous: false,
    authorName: "Rafiq Ahmed",
    workLifeRating: 4,
    salaryRating: 5,
    managementRating: 4,
    reviewText:
      "Salary increment is generous compared to other local IT firms. The technical team is strong and there are real learning opportunities. My only complaint is that some departments are still a bit siloed.",
    voteScore: 11,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    companyId: 2,
    isAnonymous: true,
    workLifeRating: 5,
    salaryRating: 4,
    managementRating: 4,
    reviewText:
      "EchoLogyx has a genuine remote-first culture. No micromanagement, results-focused. The salary was slightly below market when I joined but they adjust based on performance. Highly recommend for people who value autonomy.",
    voteScore: 18,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Salary data — Salaries page er jonno aggregated mock
export const MOCK_SALARY_BENCHMARKS = [
  { role: "Junior Software Engineer", avgMin: 25000, avgMax: 45000, sampleCount: 48, city: "Chattogram" },
  { role: "Mid-Level Software Engineer", avgMin: 45000, avgMax: 80000, sampleCount: 72, city: "Chattogram" },
  { role: "Senior Software Engineer", avgMin: 80000, avgMax: 150000, sampleCount: 31, city: "Chattogram" },
  { role: "Frontend Developer (React)", avgMin: 30000, avgMax: 70000, sampleCount: 39, city: "Chattogram" },
  { role: "Backend Developer (Node.js)", avgMin: 35000, avgMax: 80000, sampleCount: 27, city: "Dhaka" },
  { role: "Full-Stack Developer", avgMin: 40000, avgMax: 90000, sampleCount: 55, city: "Dhaka" },
  { role: "DevOps Engineer", avgMin: 60000, avgMax: 130000, sampleCount: 19, city: "Dhaka" },
  { role: "UI/UX Designer", avgMin: 25000, avgMax: 55000, sampleCount: 22, city: "Chattogram" },
  { role: "Mobile Developer (Flutter)", avgMin: 35000, avgMax: 75000, sampleCount: 16, city: "Dhaka" },
  { role: "Project Manager", avgMin: 60000, avgMax: 120000, sampleCount: 14, city: "Dhaka" },
  { role: "QA Engineer", avgMin: 20000, avgMax: 45000, sampleCount: 33, city: "Chattogram" },
  { role: "Data Scientist", avgMin: 50000, avgMax: 110000, sampleCount: 11, city: "Dhaka" },
];
