// prisma/seed-data/companies.js
const companies = [
  {
    companyName: "Blendin",
    websiteDomain: "blendin247.com",
    contactEmail: "mail@blendin247.com",
    location: "Agrabad, Chittagong",
    address: "1719 Sheikh Mujib Road, Agrabad, Chittagong, Bangladesh",
    facebookUrl: "https://www.facebook.com/blendin247",
    linkedinUrl: "https://www.linkedin.com/company/blendin247",
    techStack: "Web Development",
    city: "Chattogram",
  },
  {
    companyName: "Xponent Infosystem",
    websiteDomain: "xponent.com.bd",
    contactEmail: "support@xponent.com.bd",
    location: "Dewanhat, Chittagong",
    address: "700/B DT Road, Nur Babhan, 2nd Floor, Dewanhat, Chittagong 4100",
    facebookUrl: "https://www.facebook.com/xponent.infosystem/",
    linkedinUrl: "https://www.linkedin.com/company/xponent-infosystem-pvt-limited",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Softrobotics",
    websiteDomain: "softrobotics.com.bd",
    contactEmail: "info@softrobotics.com.bd",
    location: "Panchlaish, Chittagong",
    address: "3rd floor, 969, East Nasirabad, CDA Avenue, Panchlaish, Chittagong",
    facebookUrl: "https://www.facebook.com/SoftroboticsBangladesh",
    techStack: "Software Development, Robotics",
    city: "Chattogram",
  },
  {
    companyName: "NextWave",
    websiteDomain: "nextwaves.agency",
    contactEmail: "info.nextwaves@gmail.com",
    location: "GEC Circle, Chittagong",
    address: "House 66, Road 06, O.R. Nizam Road R/A, GEC Circle, Panchlaish, Chittagong",
    facebookUrl: "https://www.facebook.com/nextwaves.agency",
    linkedinUrl: "https://www.linkedin.com/company/nextwavesagency",
    techStack: "Digital Agency, Web Development",
    city: "Chattogram",
  },
  {
    companyName: "F.A. Creative Firm Ltd",
    websiteDomain: "facreative.biz",
    contactEmail: "support@facreative.biz",
    location: "Andorkilla, Chittagong",
    address: "Shikkhok Bhaban (4th Floor: East), Andorkilla Square, Chittagong",
    facebookUrl: "https://www.facebook.com/facreative.biz",
    techStack: "Creative, Web Design",
    city: "Chattogram",
  },
  {
    companyName: "EchoLogyx Ltd",
    websiteDomain: "echologyx.com",
    contactEmail: "info@echologyx.com",
    location: "Nasirabad, Chittagong",
    address: "House-21, Road-01, Block-B, CDA R/A, Chandgaon, Chittagong",
    facebookUrl: "https://www.facebook.com/EchoLogyx",
    linkedinUrl: "https://www.linkedin.com/company/echologyx",
    techStack: "CRO, Web Development",
    city: "Chattogram",
  },
  {
    companyName: "Brain Station 23",
    websiteDomain: "brainstation-23.com",
    contactEmail: "sales@brainstation-23.com",
    location: "Mohakhali, Dhaka",
    address: "8th Floor, Plot-02, Outering Road, Amtoli, Mohakhali, Dhaka",
    facebookUrl: "https://www.facebook.com/brainstation23",
    linkedinUrl: "https://www.linkedin.com/company/brain-station-23",
    techStack: "React, Node.js, .NET, Python, Flutter",
    city: "Dhaka",
  },
  {
    companyName: "Kaz Software",
    websiteDomain: "kaz.com.bd",
    contactEmail: "info@kaz.com.bd",
    location: "Dhanmondi, Dhaka",
    address: "House 35, Road 2, Dhanmondi, Dhaka",
    facebookUrl: "https://www.facebook.com/kazsoftware",
    linkedinUrl: "https://www.linkedin.com/company/kaz-software",
    techStack: "Python, Django, React, Web Development",
    city: "Dhaka",
  },
  {
    companyName: "TigerIT Bangladesh Ltd",
    websiteDomain: "tigerit.com",
    contactEmail: "info@tigerit.com",
    location: "Banani, Dhaka",
    address: "House 9, Road 11, Block F, Banani, Dhaka",
    facebookUrl: "https://www.facebook.com/tigeritbd",
    linkedinUrl: "https://www.linkedin.com/company/tigerit-bangladesh-ltd.",
    techStack: "Biometrics, Java, C++, Systems Programming",
    city: "Dhaka",
  },
  {
    companyName: "Therap (BD) Ltd",
    websiteDomain: "therapbd.com",
    contactEmail: "info@therapbd.com",
    location: "Baniapara, Sylhet",
    address: "House 12, Road 4, Sector 3, Uttara, Dhaka & Sylhet Hub",
    techStack: "Java, Oracle, Enterprise Software",
    city: "Sylhet",
  }
];

module.exports = { companies };
