// TechTribe Company Seed Data
// Bangladeshi IT firm list theke parse kora data — Chattogram, Dhaka, Sylhet cover kora hoyeche

export const companies = [
  // ─── CHATTOGRAM ───────────────────────────────────────────────────────────
  {
    companyName: "Blendin",
    websiteDomain: "blendin247.com",
    contactEmail: "mail@blendin247.com",
    location: "Agrabad, Chittagong",
    address: "1719 Sheikh Mujib Road, Agrabad, Chittagong, Bangladesh",
    facebookUrl: "https://www.facebook.com/blendin247",
    linkedinUrl: "https://www.linkedin.com/company/blendin247",
    techStack: "Web Development",
    city: "Chattogram",
  },
  {
    companyName: "Xponent Infosystem",
    websiteDomain: "xponent.com.bd",
    contactEmail: "support@xponent.com.bd",
    location: "Dewanhat, Chittagong",
    address: "700/B DT Road, Nur Babhan, 2nd Floor, Dewanhat, Chittagong 4100",
    facebookUrl: "https://www.facebook.com/xponent.infosystem/",
    linkedinUrl: "https://www.linkedin.com/company/xponent-infosystem-pvt-limited",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Softrobotics",
    websiteDomain: "softrobotics.com.bd",
    contactEmail: "info@softrobotics.com.bd",
    location: "Panchlaish, Chittagong",
    address: "3rd floor, 969, East Nasirabad, CDA Avenue, Panchlaish, Chittagong",
    facebookUrl: "https://www.facebook.com/SoftroboticsBangladesh",
    techStack: "Software Development, Robotics",
    city: "Chattogram",
  },
  {
    companyName: "NextWave",
    websiteDomain: "nextwaves.agency",
    contactEmail: "info.nextwaves@gmail.com",
    location: "GEC Circle, Chittagong",
    address: "House 66, Road 06, O.R. Nizam Road R/A, GEC Circle, Panchlaish, Chittagong",
    facebookUrl: "https://www.facebook.com/nextwaves.agency",
    linkedinUrl: "https://www.linkedin.com/company/nextwavesagency",
    techStack: "Digital Agency, Web Development",
    city: "Chattogram",
  },
  {
    companyName: "F.A. Creative Firm Ltd",
    websiteDomain: "facreative.biz",
    contactEmail: "support@facreative.biz",
    location: "Andorkilla, Chittagong",
    address: "Shikkhok Bhaban (4th Floor: East), Andorkilla Square, Chittagong",
    facebookUrl: "https://www.facebook.com/facreative.biz",
    techStack: "Creative, Web Design",
    city: "Chattogram",
  },
  {
    companyName: "EchoLogyx Ltd",
    websiteDomain: "echologyx.com",
    contactEmail: "hello@echologyx.com",
    location: "Muradpur, Chattogram",
    address: "Jumairah Fairmont Trade Centre, 327 Old CDA Avenue, Muradpur, Chattogram",
    facebookUrl: "https://www.facebook.com/echologyxltd/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Bit Code Technologies Limited",
    websiteDomain: "bitcode.pro",
    location: "Khulshi, Chittagong",
    address: "J Noor Tower, 2nd floor, Flat no 3, 9 no Road, Nasirabad Properties, Khulshi, Chattogram",
    facebookUrl: "https://www.facebook.com/bitcodetechnologiesltd",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "DotCamp",
    websiteDomain: "dotcamp.com",
    location: "Remote",
    address: "Remote Company",
    facebookUrl: "https://www.facebook.com/dotcamphq",
    techStack: "Remote, Web Development",
    city: "Chattogram",
    notes: "Remote company, does not hire interns",
  },
  {
    companyName: "LionCoders",
    websiteDomain: "lion-coders.com",
    contactEmail: "support@lion-coders.com",
    location: "Agrabad, Chittagong",
    address: "Bhandar Market (7th Floor), Sheikh Mujib Road, Chittagong",
    facebookUrl: "https://www.facebook.com/lioncoders",
    linkedinUrl: "https://www.linkedin.com/company/lioncoders/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "W3 Eden",
    websiteDomain: "w3eden.com",
    contactEmail: "contact@w3eden.com",
    location: "Kalpolok, Chittagong",
    address: "House D59, Road 1, Lane 4, Kalpolok, Chittagong",
    facebookUrl: "https://www.facebook.com/w3edeninc",
    linkedinUrl: "https://www.linkedin.com/company/w3eden/",
    techStack: "WordPress, Web Development",
    city: "Chattogram",
  },
  {
    companyName: "Webermelon",
    websiteDomain: "webermelon.com",
    contactEmail: "info@webermelon.com",
    location: "Khulshi, Chattogram",
    address: "51/A, Tahrub Tower, 3 No. Jakir Hossain Road, S Khulshi Rd, Chattogram",
    facebookUrl: "https://www.facebook.com/Webermelon/",
    linkedinUrl: "https://www.linkedin.com/company/webermelon/",
    techStack: "Web Development, Design",
    city: "Chattogram",
  },
  {
    companyName: "Authentic Four Technology",
    websiteDomain: "authenticfour.com",
    contactEmail: "info@authenticfour.com",
    location: "Agrabad, Chattogram",
    address: "Level 9, Software Technology Park, Agrabad, Chattogram",
    facebookUrl: "https://www.facebook.com/authenticfour",
    linkedinUrl: "https://www.linkedin.com/company/authentic-four-technology/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Coders Lab",
    websiteDomain: "coderslab.com.bd",
    contactEmail: "info@coderslab.com.bd",
    location: "Agrabad, Chattogram",
    address: "Level-10 Chittagong Software Technology Park, Chattogram",
    facebookUrl: "https://www.facebook.com/official.coderslab.com.bd/",
    linkedinUrl: "https://www.linkedin.com/company/coders-lab-com-bd/",
    techStack: "Software Development, Training",
    city: "Chattogram",
  },
  {
    companyName: "Smart Framework",
    websiteDomain: "smartframeworkbd.com",
    contactEmail: "info@smartframeworkbd.com",
    location: "Agrabad, Chattogram",
    address: "312, 4th floor, Rani Bhaban, Behind Hasan Ali Jame Masjid, S.K. Mujib Road, Chattogram",
    facebookUrl: "https://www.facebook.com/smartframework",
    linkedinUrl: "https://www.linkedin.com/company/smart-framework/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "mPair Technologies",
    websiteDomain: "mpairtech.com",
    contactEmail: "info@mpairtech.com",
    location: "Agrabad, Chattogram",
    address: "932 Late Alhaj Zahur Ahmed Chowdhury Rd, Chattogram 4000",
    facebookUrl: "https://www.facebook.com/mPairtechnologies/",
    linkedinUrl: "https://www.linkedin.com/company/mpair-technologies/",
    techStack: "Software Development, Mobile",
    city: "Chattogram",
  },
  {
    companyName: "Spinner Tech",
    websiteDomain: "spinnertech.dev",
    contactEmail: "spinnertechworld@gmail.com",
    location: "GEC Circle, Chattogram",
    address: "Beside Sanmar, House:107, Road:9 O.R. Nizam Road, Chattogram 4203",
    facebookUrl: "https://www.facebook.com/spinnertechlimited/",
    linkedinUrl: "https://www.linkedin.com/company/spinner-tech-bd/",
    techStack: "Web Development",
    city: "Chattogram",
  },
  {
    companyName: "Z-Eight Tech",
    websiteDomain: "z8tech.dev",
    contactEmail: "z8techh@gmail.com",
    location: "GEC Circle, Chattogram",
    address: "House no.-1332, O.R. Nizam Road GEC, Chattogram",
    facebookUrl: "https://www.facebook.com/z8tech",
    linkedinUrl: "https://www.linkedin.com/company/z-eight-tech/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Cursor Limited",
    websiteDomain: "cursorbd.com",
    contactEmail: "hello@arduix.com",
    location: "Panchlaish, Chattogram",
    address: "28, Panchlaish R/A, Opposite King of Chittagong Club, Chattogram-4203",
    facebookUrl: "https://www.facebook.com/CURSORBD",
    linkedinUrl: "https://www.linkedin.com/company/cursor-limited-ctg/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Ali Technology",
    websiteDomain: "alitechbd.com",
    contactEmail: "info@alitechbd.com",
    location: "GEC Circle, Chattogram",
    address: "H# 03(4-A) Road# 33, O.R. Nizam Road R/A GEC, Chattogram",
    facebookUrl: "https://www.facebook.com/alitechbd",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Liberate Labs",
    websiteDomain: "liberate-labs.com",
    contactEmail: "contact@liberate-labs.com",
    location: "Panchlaish, Chattogram",
    address: "82 Chatteshwari Rd, Chattogram",
    facebookUrl: "https://www.facebook.com/liberatelabs.bangladesh/",
    linkedinUrl: "https://www.linkedin.com/company/liberatelabs/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "DataPollex",
    websiteDomain: "datapollex.com",
    contactEmail: "contact@datapollex.com",
    location: "Khulshi, Chattogram",
    address: "Sweet Home Red Rose, Block-C, Lane-03, 572, Road-1 S Khulshi Rd, Chattogram",
    facebookUrl: "https://www.facebook.com/datapollex",
    linkedinUrl: "https://www.linkedin.com/company/datapollex/",
    techStack: "Data Science, Software Development",
    city: "Chattogram",
  },
  {
    companyName: "RILO IT & Software Ltd",
    websiteDomain: "it.rilogroup.com",
    contactEmail: "it@rilogroup.com",
    location: "Halishahar, Chattogram",
    address: "Imperial Plaza, Suit # B-2(2nd floor), Plot-725/A, Port Connecting Road, Halishahar, Chattogram",
    techStack: "IT Solutions",
    city: "Chattogram",
  },
  {
    companyName: "Faarns Ltd",
    websiteDomain: "faarns.com",
    contactEmail: "faisal@faarns.com",
    location: "Chattogram",
    facebookUrl: "https://www.facebook.com/profile.php?id=61554518447880",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Xentro BD",
    websiteDomain: "xentrobd.com",
    contactEmail: "info@xentrobd.com",
    location: "Khulshi, Chittagong",
    address: "Abdul Hannan Road, Khulshi Colony, Chittagong",
    facebookUrl: "https://www.facebook.com/xentrobd",
    linkedinUrl: "https://www.linkedin.com/company/xentro/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "SM IT Solution",
    websiteDomain: "smitsolution.com.bd",
    contactEmail: "info@smitsolution.com.bd",
    location: "Khulshi, Chittagong",
    address: "R-1, House 2, Nasirabad Properties LTD, South Khulshi, Chittagong",
    facebookUrl: "https://www.facebook.com/smitsolution.uae",
    linkedinUrl: "https://www.linkedin.com/company/smitsolution/",
    techStack: "IT Solutions",
    city: "Chattogram",
  },
  {
    companyName: "Tirzok Private Limited",
    websiteDomain: "tirzok.com",
    contactEmail: "info@tirzok.com",
    location: "Chattogram",
    facebookUrl: "https://www.facebook.com/share/1D4mZExGRK/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Zentexx",
    websiteDomain: "zentexx.com",
    contactEmail: "contact@zentexx.com",
    location: "Nandankanan, Chattogram",
    address: "97 Buddhist Temple Road, Nandankanan, Chattogram",
    linkedinUrl: "https://www.linkedin.com/company/zentexx/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "LabFry Technologies",
    websiteDomain: "labfry.com",
    contactEmail: "hr@labfry.com",
    location: "Moulovi Pukur Par, Chittagong",
    address: "MK Tower, Moulovi Pukur Par, near Al Hekmah International School, Chittagong",
    facebookUrl: "https://www.facebook.com/labfrytechnology/",
    linkedinUrl: "https://www.linkedin.com/company/labfry/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Ultimate IT Solutions Ltd",
    websiteDomain: "ultimateit-bd.com",
    contactEmail: "info@ultimateit-bd.com",
    location: "Cheragi Pahar, Chattogram",
    address: "Azadi Tower (6th floor), 2 Momin Road, Cheragi Pahar, Kotwali, Chattogram-4000",
    facebookUrl: "https://www.facebook.com/ultimateitbd/",
    linkedinUrl: "https://www.linkedin.com/company/ultimate-it-solution-ltd/",
    techStack: "IT Solutions",
    city: "Chattogram",
  },
  {
    companyName: "Patricius IT",
    websiteDomain: "patriciusit.com",
    contactEmail: "contact@patriciusit.com",
    location: "East High Level Rd, Chattogram",
    address: "(5th floor) 90, M B Complex, East High Level Rd, Chattogram 4225",
    facebookUrl: "https://www.facebook.com/patriciusit",
    linkedinUrl: "https://www.linkedin.com/company/patricius-it/",
    techStack: "IT Solutions, Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Alchemy Software",
    websiteDomain: "alchemy-bd.com",
    contactEmail: "alchemysoftware@yahoo.com",
    location: "Lalkhan Bazar, Chittagong",
    address: "335 (6th floor), CDA Avenue, Lalkhan Bazar, Chittagong",
    facebookUrl: "https://www.facebook.com/AlchemySoftwareLimited",
    linkedinUrl: "https://www.linkedin.com/company/alchemysoftwarelimited/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Genuine Technology & Research Ltd",
    websiteDomain: "gtrbd.com",
    contactEmail: "info@gtrbd.com",
    location: "High Level Road, Chattogram",
    address: "2nd floor, Omar Karim Tower, 113 High Level Road, Chattogram 4000",
    facebookUrl: "https://www.facebook.com/gtr.bd.official/",
    linkedinUrl: "https://www.linkedin.com/company/genuine-technology-research-ltd-/",
    techStack: "Technology Research, Software",
    city: "Chattogram",
  },
  {
    companyName: "iniAstra Tech",
    websiteDomain: "iniastratech.com",
    contactEmail: "info@iniastratech.com",
    location: "World Trade Center, Chattogram",
    address: "World Trade Center, Chattogram",
    facebookUrl: "https://www.facebook.com/iniastratech",
    linkedinUrl: "https://www.linkedin.com/company/iniastratech/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Hello World IT",
    websiteDomain: "helloworldbd.com",
    contactEmail: "hrd@helloworldbd.com",
    location: "Dhaniwalapara, Chattogram",
    address: "1st floor (Municipal Shopping Complex), D.T Road, Dhaniwalapara, Chattogram",
    facebookUrl: "https://www.facebook.com/helloworldcomms/",
    linkedinUrl: "https://www.linkedin.com/company/hello-world-communications-limmited/",
    techStack: "IT, Communications",
    city: "Chattogram",
  },
  {
    companyName: "SDR Software Development & Research",
    websiteDomain: "sdrbd.net",
    contactEmail: "info@sdrbd.net",
    location: "Mehedibag, Chattogram",
    address: "CHEORA HOUSE, 581/A MEHEDIBAG ROAD, MEHEDIBAG, CHATTOGRAM",
    facebookUrl: "https://www.facebook.com/sdrbd01",
    linkedinUrl: "https://www.linkedin.com/company/sdrbd01/",
    techStack: "Software Development, Research",
    city: "Chattogram",
  },
  {
    companyName: "Lead Bangladesh",
    websiteDomain: "leadbangladesh.com",
    contactEmail: "office@leadbangladesh.com",
    location: "GEC Circle, Chittagong",
    address: "House 08, Road 01, O.R. Nizam R/A, GEC, Chittagong",
    facebookUrl: "https://www.facebook.com/LeadBangladesh",
    linkedinUrl: "https://www.linkedin.com/company/leadbdgroup/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Xceed Bangladesh Ltd",
    websiteDomain: "xceedbd.com",
    contactEmail: "xceedbd@gmail.com",
    location: "Agrabad, Chattogram",
    address: "Chattogram Software Technology Park (Level 9), Agrabad, Chattogram – 4100",
    facebookUrl: "https://www.facebook.com/xceedbd/",
    linkedinUrl: "https://www.linkedin.com/company/xceedbd/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Skylark Soft Limited",
    websiteDomain: "skylarksoft.com",
    contactEmail: "info@skylarksoft.com",
    location: "Hill View Housing Society, Chattogram",
    address: "House: 20/B, Road: 02, Hill View Housing Society, Chattogram 4209",
    facebookUrl: "https://www.facebook.com/skylarksoft/",
    linkedinUrl: "https://www.linkedin.com/company/skylark-soft-limited/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "ITL Digital Technology",
    websiteDomain: "itldigitaltech.com",
    contactEmail: "support@itldigitaltech.com",
    location: "Hill View Housing Society, GEC, Chattogram",
    address: "Road No# 04, Hill View Housing Society, GEC, Chattogram",
    facebookUrl: "https://www.facebook.com/itldt",
    linkedinUrl: "https://www.linkedin.com/company/idt2015/",
    techStack: "Digital Technology, IT",
    city: "Chattogram",
  },
  {
    companyName: "Spider IT Bangladesh",
    websiteDomain: "bdspiderit.com",
    contactEmail: "spideritbangladesh@gmail.com",
    location: "Nasirabad, Chittagong",
    address: "Nasirabad Housing Society, 5 No Road, Chittagong",
    facebookUrl: "https://www.facebook.com/SPIDERIT01/",
    linkedinUrl: "https://www.linkedin.com/company/spider-it-bangladesh/",
    techStack: "IT Solutions",
    city: "Chattogram",
  },
  {
    companyName: "RM IT Ltd",
    websiteDomain: "rmitltd.com",
    contactEmail: "info@rmitltd.com",
    location: "GEC Circle, Chattogram",
    address: "510 Central Plaza (5th floor), O.R Nizam Road Circle, Chattogram 4000",
    facebookUrl: "https://www.facebook.com/rmitltd/",
    linkedinUrl: "https://www.linkedin.com/company/rmitltd/",
    techStack: "IT Solutions",
    city: "Chattogram",
  },
  {
    companyName: "HeyDev",
    websiteDomain: "heydev.net",
    contactEmail: "hello@heydev.xyz",
    location: "Lalkhan Bazaar, Chittagong",
    address: "Highway Society, Lalkhan Bazaar, Chittagong",
    facebookUrl: "https://www.facebook.com/heydevnet",
    linkedinUrl: "https://www.linkedin.com/company/heydevnet/",
    techStack: "Web Development, Software",
    city: "Chattogram",
  },
  {
    companyName: "EcoSoftBD",
    websiteDomain: "ecosoftbd.com",
    contactEmail: "sales@ecosoftbdit.com",
    location: "Bakolia, Chattogram",
    address: "F-504, Kolpolok R/A, Bakolia, Chattogram",
    facebookUrl: "https://www.facebook.com/ecosoftbd",
    linkedinUrl: "https://www.linkedin.com/company/ecosoftbd/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Magnetism Tech Limited",
    websiteDomain: "magnetismtech.com",
    contactEmail: "info@magnetismtech.com",
    location: "Strand Road, Chittagong",
    address: "Amin Future Park (5th Floor) 1440/A, Strand Road Barik Building Circle, Chittagong",
    facebookUrl: "https://www.facebook.com/profile.php?id=61578025675753",
    linkedinUrl: "https://www.linkedin.com/company/magnetism-tech-limited/",
    techStack: "Technology Solutions",
    city: "Chattogram",
  },
  {
    companyName: "Extreme Solutions",
    websiteDomain: "extreme.com.bd",
    contactEmail: "info@extreme.com.bd",
    location: "Agrabad, Chittagong",
    address: "771 Sheikh Mujib Road, Agrabad, Chittagong, 4100",
    facebookUrl: "https://www.facebook.com/SoftwareCompanyBangladesh",
    linkedinUrl: "https://www.linkedin.com/company/extreme-solutions-bd/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "SA Tech & Consultancy",
    websiteDomain: "satech-bd.com",
    contactEmail: "info@satech-bd.com",
    location: "Jamalkhan, Chattogram",
    address: "112 Sunmar Spring Garden, Jamalkhan Road, Chattogram",
    facebookUrl: "https://www.facebook.com/SATechandconsultancybd",
    linkedinUrl: "https://www.linkedin.com/company/sa-tech-consultancy/",
    techStack: "Technology, Consultancy",
    city: "Chattogram",
  },
  {
    companyName: "Trust Global Communications",
    websiteDomain: "trustglobalcommunications.com",
    contactEmail: "services@trustglobalcommunications.com",
    location: "Agrabad, Chattogram",
    address: "Level 10, Chattogram Software Technology Park, Agrabad, Chattogram",
    facebookUrl: "https://www.facebook.com/TrustGlobalCommunications/",
    linkedinUrl: "https://www.linkedin.com/company/trust-globalcommunications/",
    techStack: "IT, Communications",
    city: "Chattogram",
  },
  {
    companyName: "Oracle Technology Software and Learning",
    websiteDomain: "otsl-ctg.com",
    contactEmail: "info@otsl-ctg.com",
    location: "Panchlaish, Chittagong",
    address: "M.M. Tower (Ground Floor), CDA Avenue (Beside Sanmar Ocean City), Panchlaish, Chittagong",
    linkedinUrl: "https://www.linkedin.com/company/otslpoint/",
    techStack: "Software, Training",
    city: "Chattogram",
  },
  {
    companyName: "BrownBrick",
    websiteDomain: "brownbrick.io",
    contactEmail: "info@brownbrick.io",
    location: "Bayezid, Chattogram",
    address: "Apt. C3, House 5, Road 6, Shangbadik H/S, Bayezid, Chattogram",
    facebookUrl: "https://www.facebook.com/brownbrickit",
    linkedinUrl: "https://www.linkedin.com/company/brownbrick/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Softviora",
    websiteDomain: "softviora.vercel.app",
    contactEmail: "softviora.oficial@gmail.com",
    location: "East Nasirabad, Chittagong",
    address: "East Nasirabad, Chittagong",
    facebookUrl: "https://www.facebook.com/profile.php?id=61561102527942",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Sanghu Group",
    websiteDomain: "sanghugroup.com",
    location: "Chawkbazar, Chittagong",
    address: "192, Chawkbazar, KB Aman Ali Road, Chittagong",
    linkedinUrl: "https://www.linkedin.com/company/sanghu-group/",
    techStack: "Technology Group",
    city: "Chattogram",
  },
  {
    companyName: "Radix Software",
    websiteDomain: "radixtech-bd.com",
    contactEmail: "info@radixtech-bd.com",
    location: "Muradpur, Chittagong",
    address: "83/86 S.N Tower, Muradpur, Chittagong",
    facebookUrl: "https://www.facebook.com/radixsoftbd",
    linkedinUrl: "https://www.linkedin.com/company/radixtechbd/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Bitesof",
    websiteDomain: "bitesoftsolution.com",
    contactEmail: "bitesoftsolution@gmail.com",
    location: "Khulshi, Chittagong",
    address: "4th floor, Hannan Tower, Khulshi Housing Society, Chittagong",
    facebookUrl: "https://www.facebook.com/bitesoftsolution",
    linkedinUrl: "https://www.linkedin.com/company/bitesoftsolution/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Softzone IT",
    websiteDomain: "softzoneit.com",
    contactEmail: "info@softzoneit.com",
    location: "Agrabad, Chittagong",
    address: "SAIMA VANDAR MARKET (6th Floor) 309 Sk. Mujib Road, Chittagong",
    facebookUrl: "https://www.facebook.com/softzoneitltd",
    linkedinUrl: "https://www.linkedin.com/company/softzoneitltd/",
    techStack: "IT Solutions",
    city: "Chattogram",
  },
  {
    companyName: "Canopus-Lab",
    websiteDomain: "canopus-lab.com",
    location: "Chittagong",
    facebookUrl: "https://www.facebook.com/canopus.lab.01",
    linkedinUrl: "https://www.linkedin.com/company/canopus-lab-01/",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "King Apps Studio",
    websiteDomain: "kingappsstudio.com",
    location: "Khulshi, Chittagong",
    address: "South Khulshi, Road 2, Chittagong",
    facebookUrl: "https://www.facebook.com/kingappsstudio",
    techStack: "Mobile Apps, Software",
    city: "Chattogram",
  },
  {
    companyName: "Dizency",
    websiteDomain: "dizency.com",
    contactEmail: "hello@dizency.com",
    location: "Hill View Housing Society, Chattogram",
    address: "Madina Tower, Block #B, Road #5, Hillview H/S, Chattogram",
    facebookUrl: "https://www.facebook.com/Dizency",
    linkedinUrl: "https://www.linkedin.com/company/dizency/",
    techStack: "Design, Web Development",
    city: "Chattogram",
  },
  {
    companyName: "Robotry Bangladesh",
    websiteDomain: "robotrybd.com",
    contactEmail: "contact@robotrybd.com",
    location: "Agrabad, Chittagong",
    address: "6th Floor, Chattogram Software Technology Park, Agrabad Access Road, Chattogram",
    facebookUrl: "https://www.facebook.com/RobotryBD",
    linkedinUrl: "https://www.linkedin.com/company/robotry-bd/",
    techStack: "Robotics, Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Makeup Coders",
    websiteDomain: "makeupcoders.com",
    contactEmail: "info@makeupcoders.com",
    location: "WASA Circle, Chattogram",
    address: "WASA Circle, MB Complex, Chattogram",
    facebookUrl: "https://www.facebook.com/makeupcoder",
    techStack: "Software Development",
    city: "Chattogram",
  },
  {
    companyName: "Error Sync",
    websiteDomain: "errorsync.com",
    contactEmail: "contact@errorsync.com",
    location: "Chattogram",
    address: "13/A, 6th floor, Nabab Siraj Ud Daula Road, Chattogram",
    facebookUrl: "https://www.facebook.com/errorsync.techonologies",
    linkedinUrl: "https://www.linkedin.com/company/error-sync/",
    techStack: "Software Development",
    city: "Chattogram",
  },

  // ─── DHAKA ────────────────────────────────────────────────────────────────
  {
    companyName: "Kaz Software Bangladesh",
    websiteDomain: "kaz.com.bd",
    contactEmail: "info@kaz.com.bd",
    location: "Shantinagar, Dhaka",
    address: "35/5 Shantinagar, Dhaka 1217",
    facebookUrl: "https://www.facebook.com/kazsoftware",
    linkedinUrl: "https://www.linkedin.com/company/kaz-software-limited/",
    phone: "01795-339300",
    techStack: "Software Development",
    city: "Dhaka",
  },
  {
    companyName: "Vivasoft Limited",
    websiteDomain: "vivasoftltd.com",
    contactEmail: "contact@vivasoftltd.com",
    location: "Kemal Ataturk Ave, Dhaka",
    address: "Floor #11,16,19 Ahmed Tower, 28, 30, Kemal Ataturk Ave, Dhaka",
    facebookUrl: "https://www.facebook.com/vivasoftltd",
    linkedinUrl: "https://www.linkedin.com/company/vivasoftltd/",
    phone: "01713-428432",
    techStack: "Software Development, Enterprise",
    city: "Dhaka",
  },
  {
    companyName: "LeadSoft Bangladesh Limited",
    websiteDomain: "leadsoft.com.bd",
    contactEmail: "info@leads-bd.com",
    location: "Mirpur, Dhaka",
    address: "LEADS Tower, M-20, Main Road 1, Section 14, Mirpur, Dhaka 1206",
    facebookUrl: "https://www.facebook.com/leadsltd",
    linkedinUrl: "https://www.linkedin.com/company/leads-corporation-limited/",
    phone: "0167 535 8575",
    techStack: "Enterprise Software, ERP",
    city: "Dhaka",
  },
  {
    companyName: "Datasoft Systems Bangladesh Limited",
    websiteDomain: "datasoft-bd.com",
    contactEmail: "info@datasoft-bd.com",
    location: "Shyamoli, Dhaka",
    address: "Rupayan Shelford (19th & 20th floor), Plot#23/6, Block#B, Mirpur Road, Shyamoli, Dhaka",
    facebookUrl: "https://www.facebook.com/DSBLFANPAGE/",
    linkedinUrl: "https://www.linkedin.com/groups/4538148/",
    techStack: "Banking Software, Enterprise",
    city: "Dhaka",
  },
  {
    companyName: "Brain Station 23",
    websiteDomain: "brainstation-23.com",
    contactEmail: "sales@brainstation-23.com",
    location: "Mohakhali, Dhaka",
    address: "8th Floor, 2 Bir Uttam AK Khandakar Road, Mohakhali C/A, Dhaka 1212",
    facebookUrl: "https://www.facebook.com/brainstation23",
    linkedinUrl: "https://www.linkedin.com/company/brainstation-23/",
    phone: "09610-902323",
    techStack: "Software Development, AI, ML, eCommerce",
    city: "Dhaka",
  },
  {
    companyName: "Smart Software Ltd",
    websiteDomain: "smartsoftware.com.bd",
    contactEmail: "hello@smartsoftware.com.bd",
    location: "Panthapath, Dhaka",
    address: "152/2/N, Panthapath, Dhaka, Bangladesh",
    facebookUrl: "https://www.facebook.com/smartsoftbd",
    linkedinUrl: "https://www.linkedin.com/company/smart-software-inc/",
    phone: "01844-047000",
    techStack: "Software Development",
    city: "Dhaka",
  },
  {
    companyName: "Bdtask Limited",
    websiteDomain: "bdtask.com",
    contactEmail: "business@bdtask.com",
    location: "Khilkhet, Dhaka",
    address: "B-25, Mannan Plaza, 4th Floor, Khilkhet, Dhaka-1229",
    facebookUrl: "https://www.facebook.com/bdtaskteam/",
    linkedinUrl: "https://www.linkedin.com/company/bdtask/",
    phone: "01958-069680",
    techStack: "Software Development, SaaS",
    city: "Dhaka",
  },
  {
    companyName: "Nano IT World",
    websiteDomain: "nanoitworld.com",
    contactEmail: "info@nanoitworld.com",
    location: "Green Road, Dhaka",
    address: "Rowshan Tower 152/2, A-2, 8th Floor Left, Green Road Panthapath, Dhaka-1250",
    facebookUrl: "https://www.facebook.com/profile.php?id=100063457633529",
    linkedinUrl: "https://www.linkedin.com/company/nano-it-world/",
    phone: "01715-147425",
    techStack: "IT Solutions",
    city: "Dhaka",
  },
  {
    companyName: "Technext Limited",
    websiteDomain: "technext.it",
    contactEmail: "info@technext.it",
    location: "Shyamoli, Dhaka",
    address: "14th floor, Rupayan Shelford, 23/6 Mirpur Rd, Shyamoli 1207, Dhaka",
    facebookUrl: "https://www.facebook.com/TechnextLimited",
    linkedinUrl: "https://www.linkedin.com/company/technextlimited/",
    phone: "1 302 433 6002",
    techStack: "SaaS, Software Development",
    city: "Dhaka",
  },

  // ─── SYLHET ───────────────────────────────────────────────────────────────
  {
    companyName: "IT Lab Solutions Ltd",
    websiteDomain: "itlabsolutions.com",
    contactEmail: "itlslhelpdesk@gmail.com",
    location: "Dhopadighirpar, Sylhet",
    address: "159 Anabil, North Dhopadighirpar 3100, Sylhet",
    facebookUrl: "https://www.facebook.com/itlabsolutionsltd",
    linkedinUrl: "https://www.linkedin.com/company/it-lab-solutions/",
    phone: "880 1842 485 222",
    techStack: "IT Solutions",
    city: "Sylhet",
  },
  {
    companyName: "AuthLab",
    websiteDomain: "authlab.io",
    contactEmail: "hello@authlab.io",
    location: "Jalalabad R/A, Sylhet",
    address: "24/A, Shah Farid Rd, Jalalabad R/A 3114, Sylhet",
    facebookUrl: "https://web.facebook.com/authLab",
    linkedinUrl: "https://www.linkedin.com/company/authlab-io/",
    phone: "01979-791001",
    techStack: "Software Development, Auth",
    city: "Sylhet",
  },
  {
    companyName: "Infinity Flame Soft",
    websiteDomain: "infinityflamesoft.com",
    contactEmail: "faisal.lu.ac@gmail.com",
    location: "Bandor Bazar, Sylhet",
    address: "513, Rangmohol Tower, Bandor Bazar, Sylhet",
    techStack: "Software Development",
    city: "Sylhet",
  },
  {
    companyName: "Sylhet IT Solutions",
    websiteDomain: "sylhetitsolution.com",
    contactEmail: "kamaletv007@gmail.com",
    location: "Lamabazar, Sylhet",
    address: "Lamabazar 3100, Sylhet",
    facebookUrl: "https://web.facebook.com/sylhetitsolution/",
    phone: "01711-067280",
    techStack: "IT Solutions",
    city: "Sylhet",
  },
];

export type CompanySeed = typeof companies[0];
